#!/usr/bin/env python

import CategoryConfig
import pysbserver

if __name__ == "__main__":
    config_path = "./"
    config_category = "pysbserver"
    config_extension = ".conf"
    
    config_object = CategoryConfig.CategoryConfig(config_path, config_category, config_extension)
    
    default_host = "*"
    doc = 'Host to bind the server to.'
    host = config_object.getOption('lobby.host', default_host, doc)
    
    default_port = "28785"
    doc = 'Port to bind the server to.'
    port = int(config_object.getOption('lobby.port', default_port, doc))
    
    default_maxclients = "5"
    doc = 'Max number of clients which can connect.'
    maxclients = int(config_object.getOption('lobby.maxclients', default_maxclients, doc))
    
    engine = pysbserver.Engine(host=host, port=port, maxclients=maxclients, maxdown=0, maxup=0)
    engine.run()